services:
    ProductService:
        class:     AppBundle\Service\ProductService
        arguments: [ "@doctrine.orm.entity_manager" ]

    ReviewService:
        class:     AppBundle\Service\ReviewService
        arguments: [ "@doctrine.orm.entity_manager" ]

    UserService:
        class:     UserBundle\Service\UserService
        arguments: [ "@doctrine.orm.entity_manager" ]

    controller.pre_execute_listener:
        class: AppBundle\Listener\ControllerListener
        tags:
          -  { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
